### ISSUE TITLE
MaxPool size 1

### ISSUE THREAD

**Issue by khornlund** [RichardBJ/Deep-Channel#3]
Hi could you explain the purpose of the MaxPooling1D layer with size 1? Is this redundant?

**Comment by numancelik34** [comment]
Hi @khornlund 
I think the pool size equals to 1, because both the size of timestep, and input features are 1 in the input shape of 1DCNN, and to apply TimeDistributed.Flatten(), MaxPooling layer is embedded before that. Let me know please if I am not correct!

**Comment by RichardBJ** [comment]
This sounds resolved so closing. Thanks
