### ISSUE TITLE
where is the file outfinaltest161.csv

### ISSUE THREAD

**Issue by magic7721** [RichardBJ/Deep-Channel#7]
No such file or directory: 'outfinaltest161.csv'

**Comment by magic7721** [comment]
sorry, i can't find the file 'outfinaltest161.csv'

**Comment by RichardBJ** [comment]
Sorry for the delat. It was just one of many training files. I have uploaded it to "random Datasets" now.

**Comment by RichardBJ** [comment]
Thank you for your interest. Closing this now
